# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

resources: 
  pipelines:
  - pipeline: sourcepipeline  # identifier for the resource used in pipeline resource variables
    source: build_pipeline  # name of the pipeline that produces an artifact
    trigger: true    # triggers aren't enabled by default unless you add trigger section to the resource

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo the source pipeline '${{ resources.pipeline.sourcepipeline.pipelineName }}'
  displayName: 'Release_Pipeline'
